package com.ssm.pojo;

import java.util.Date;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTENDANCE.ATTENDANCE_ID
     *
     * @mbg.generated
     */
    private Integer attendanceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTENDANCE.STUDENT_ID
     *
     * @mbg.generated
     */
    private Integer studentId;
    private String studentName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTENDANCE.CLASS_ID
     *
     * @mbg.generated
     */
    private Integer classId;
    private String className;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTENDANCE.ATTENDANCE_DATE
     *
     * @mbg.generated
     */
    private Date attendanceDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ATTENDANCE.STATUS
     *
     * @mbg.generated
     */
    private String status;

    public Attendance(){}
    public Attendance(Integer attendanceId, Integer studentId, Integer classId, Date attendanceDate, String status) {
        this.attendanceId = attendanceId;
        this.studentId = studentId;
        this.classId = classId;
        this.attendanceDate = attendanceDate;
        this.status = status;
    }

    @Override
    public String toString() {
        return "Attendance{" +
                "attendanceId=" + attendanceId +
                ", studentId=" + studentId +
                ", studentName='" + studentName + '\'' +
                ", classId=" + classId +
                ", className='" + className + '\'' +
                ", attendanceDate=" + attendanceDate +
                ", status='" + status + '\'' +
                '}';
    }

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTENDANCE.ATTENDANCE_ID
     *
     * @return the value of ATTENDANCE.ATTENDANCE_ID
     *
     * @mbg.generated
     */
    public Integer getAttendanceId() {
        return attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTENDANCE.ATTENDANCE_ID
     *
     * @param attendanceId the value for ATTENDANCE.ATTENDANCE_ID
     *
     * @mbg.generated
     */
    public void setAttendanceId(Integer attendanceId) {
        this.attendanceId = attendanceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTENDANCE.STUDENT_ID
     *
     * @return the value of ATTENDANCE.STUDENT_ID
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTENDANCE.STUDENT_ID
     *
     * @param studentId the value for ATTENDANCE.STUDENT_ID
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTENDANCE.CLASS_ID
     *
     * @return the value of ATTENDANCE.CLASS_ID
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTENDANCE.CLASS_ID
     *
     * @param classId the value for ATTENDANCE.CLASS_ID
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTENDANCE.ATTENDANCE_DATE
     *
     * @return the value of ATTENDANCE.ATTENDANCE_DATE
     *
     * @mbg.generated
     */
    public Date getAttendanceDate() {
        return attendanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTENDANCE.ATTENDANCE_DATE
     *
     * @param attendanceDate the value for ATTENDANCE.ATTENDANCE_DATE
     *
     * @mbg.generated
     */
    public void setAttendanceDate(Date attendanceDate) {
        this.attendanceDate = attendanceDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ATTENDANCE.STATUS
     *
     * @return the value of ATTENDANCE.STATUS
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ATTENDANCE.STATUS
     *
     * @param status the value for ATTENDANCE.STATUS
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}