package com.ssm.pojo;

import java.text.SimpleDateFormat;
import java.util.Date;

public class Interview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTERVIEW.INTERVIEW_ID
     *
     * @mbg.generated
     */
    private Integer interviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTERVIEW.STUDENT_ID
     *
     * @mbg.generated
     */
    private Integer studentId;
    private String studentName;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTERVIEW.CLASS_ID
     *
     * @mbg.generated
     */
    private Integer classId;
    private String className;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTERVIEW.INTERVIEW_DATE
     *
     * @mbg.generated
     */
    private Date interviewDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INTERVIEW.INTERVIEW_CONTENT
     *
     * @mbg.generated
     */
    private String interviewContent;


    public Interview(){}
    public Interview(Integer studentId, Integer classId, Date interviewDate, String interviewContent) {
        this.studentId = studentId;
        this.classId = classId;
        this.interviewDate = interviewDate;
        this.interviewContent = interviewContent;
    }

    @Override
    public String toString() {
        return "Interview{" +
                "interviewId=" + interviewId +
                ", studentId=" + studentId +
                ", studentName='" + studentName + '\'' +
                ", classId=" + classId +
                ", className='" + className + '\'' +
                ", interviewDate=" + interviewDate +
                ", interviewContent='" + interviewContent + '\'' +
                '}';
    }

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTERVIEW.INTERVIEW_ID
     *
     * @return the value of INTERVIEW.INTERVIEW_ID
     *
     * @mbg.generated
     */


    public Integer getInterviewId() {
        return interviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTERVIEW.INTERVIEW_ID
     *
     * @param interviewId the value for INTERVIEW.INTERVIEW_ID
     *
     * @mbg.generated
     */
    public void setInterviewId(Integer interviewId) {
        this.interviewId = interviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTERVIEW.STUDENT_ID
     *
     * @return the value of INTERVIEW.STUDENT_ID
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTERVIEW.STUDENT_ID
     *
     * @param studentId the value for INTERVIEW.STUDENT_ID
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTERVIEW.CLASS_ID
     *
     * @return the value of INTERVIEW.CLASS_ID
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTERVIEW.CLASS_ID
     *
     * @param classId the value for INTERVIEW.CLASS_ID
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTERVIEW.INTERVIEW_DATE
     *
     * @return the value of INTERVIEW.INTERVIEW_DATE
     *
     * @mbg.generated
     */
    public Date getInterviewDate() {
        return interviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTERVIEW.INTERVIEW_DATE
     *
     * @param interviewDate the value for INTERVIEW.INTERVIEW_DATE
     *
     * @mbg.generated
     */
    public void setInterviewDate(Date interviewDate) {
        this.interviewDate = interviewDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INTERVIEW.INTERVIEW_CONTENT
     *
     * @return the value of INTERVIEW.INTERVIEW_CONTENT
     *
     * @mbg.generated
     */
    public String getInterviewContent() {
        return interviewContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INTERVIEW.INTERVIEW_CONTENT
     *
     * @param interviewContent the value for INTERVIEW.INTERVIEW_CONTENT
     *
     * @mbg.generated
     */
    public void setInterviewContent(String interviewContent) {
        this.interviewContent = interviewContent;
    }
}