package com.ssm.pojo;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_ID
     *
     * @mbg.generated
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_NAME
     *
     * @mbg.generated
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.CLASS_ID
     *
     * @mbg.generated
     */
    private String className;
    private Integer classId;

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_SEX
     *
     * @mbg.generated
     */
    private String studentSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_SCHOOL
     *
     * @mbg.generated
     */
    private String studentSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_EDUCATION
     *
     * @mbg.generated
     */
    private String studentEducation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_MAJOR
     *
     * @mbg.generated
     */
    private String studentMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_NATIVE
     *
     * @mbg.generated
     */
    private String studentNative;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_TEL
     *
     * @mbg.generated
     */
    private Integer studentTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT.STUDENT_QQ
     *
     * @mbg.generated
     */
    private Integer studentQq;


    public Student(){}

    public Student(Integer studentId, String studentName, String className, Integer classId, String studentSex, String studentSchool, String studentEducation, String studentMajor, String studentNative, Integer studentTel, Integer studentQq) {
        this.studentId = studentId;
        this.studentName = studentName;
        this.className = className;
        this.classId = classId;
        this.studentSex = studentSex;
        this.studentSchool = studentSchool;
        this.studentEducation = studentEducation;
        this.studentMajor = studentMajor;
        this.studentNative = studentNative;
        this.studentTel = studentTel;
        this.studentQq = studentQq;
    }

    @Override
    public String toString() {
        return "Student{" +
                "studentId=" + studentId +
                ", studentName='" + studentName + '\'' +
                ", className=" + className +
                ", studentSex='" + studentSex + '\'' +
                ", studentSchool='" + studentSchool + '\'' +
                ", studentEducation='" + studentEducation + '\'' +
                ", studentMajor='" + studentMajor + '\'' +
                ", studentNative='" + studentNative + '\'' +
                ", studentTel=" + studentTel +
                ", studentQq=" + studentQq +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_ID
     *
     * @return the value of STUDENT.STUDENT_ID
     *
     * @mbg.generated
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_ID
     *
     * @param studentId the value for STUDENT.STUDENT_ID
     *
     * @mbg.generated
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_NAME
     *
     * @return the value of STUDENT.STUDENT_NAME
     *
     * @mbg.generated
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_NAME
     *
     * @param studentName the value for STUDENT.STUDENT_NAME
     *
     * @mbg.generated
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.CLASS_ID
     *
     * @return the value of STUDENT.CLASS_ID
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_SEX
     *
     * @return the value of STUDENT.STUDENT_SEX
     *
     * @mbg.generated
     */
    public String getStudentSex() {
        return studentSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_SEX
     *
     * @param studentSex the value for STUDENT.STUDENT_SEX
     *
     * @mbg.generated
     */
    public void setStudentSex(String studentSex) {
        this.studentSex = studentSex == null ? null : studentSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_SCHOOL
     *
     * @return the value of STUDENT.STUDENT_SCHOOL
     *
     * @mbg.generated
     */
    public String getStudentSchool() {
        return studentSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_SCHOOL
     *
     * @param studentSchool the value for STUDENT.STUDENT_SCHOOL
     *
     * @mbg.generated
     */
    public void setStudentSchool(String studentSchool) {
        this.studentSchool = studentSchool == null ? null : studentSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_EDUCATION
     *
     * @return the value of STUDENT.STUDENT_EDUCATION
     *
     * @mbg.generated
     */
    public String getStudentEducation() {
        return studentEducation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_EDUCATION
     *
     * @param studentEducation the value for STUDENT.STUDENT_EDUCATION
     *
     * @mbg.generated
     */
    public void setStudentEducation(String studentEducation) {
        this.studentEducation = studentEducation == null ? null : studentEducation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_MAJOR
     *
     * @return the value of STUDENT.STUDENT_MAJOR
     *
     * @mbg.generated
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_MAJOR
     *
     * @param studentMajor the value for STUDENT.STUDENT_MAJOR
     *
     * @mbg.generated
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_NATIVE
     *
     * @return the value of STUDENT.STUDENT_NATIVE
     *
     * @mbg.generated
     */
    public String getStudentNative() {
        return studentNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_NATIVE
     *
     * @param studentNative the value for STUDENT.STUDENT_NATIVE
     *
     * @mbg.generated
     */
    public void setStudentNative(String studentNative) {
        this.studentNative = studentNative == null ? null : studentNative.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_TEL
     *
     * @return the value of STUDENT.STUDENT_TEL
     *
     * @mbg.generated
     */
    public Integer getStudentTel() {
        return studentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_TEL
     *
     * @param studentTel the value for STUDENT.STUDENT_TEL
     *
     * @mbg.generated
     */
    public void setStudentTel(Integer studentTel) {
        this.studentTel = studentTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT.STUDENT_QQ
     *
     * @return the value of STUDENT.STUDENT_QQ
     *
     * @mbg.generated
     */
    public Integer getStudentQq() {
        return studentQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT.STUDENT_QQ
     *
     * @param studentQq the value for STUDENT.STUDENT_QQ
     *
     * @mbg.generated
     */
    public void setStudentQq(Integer studentQq) {
        this.studentQq = studentQq;
    }


}